# @copyright Copyright (c) contributors to Project Ocre,
# which has been established as Project Ocre a Series of LF Projects, LLC
#
# SPDX-License-Identifier: Apache-2.0

manifest:
  projects:
    - name: zephyr
      revision: v4.3.0
      url: https://github.com/zephyrproject-rtos/zephyr
      west-commands: scripts/west-commands.yml
      import:
        name-allowlist:
          - littlefs
          - picolibc
          - hal_stm32
          - hal_st
          - hal_nordic
          - hal_rpi_pico
          - cmsis_6
  self:
    path: ocre-runtime
