manifest:
  projects:
    - name: zephyr
      revision: main
      url: https://github.com/zephyrproject-rtos/zephyr
      west-commands: scripts/west-commands.yml
      import: true
    - name: wasm-micro-runtime
      revision: main
      url: https://github.com/bytecodealliance/wasm-micro-runtime
      path: wasm-micro-runtime
      
  self:
    path: application   
