manifest:
  projects:
    - name: zephyr
      revision: v4.2-branch
      url: https://github.com/zephyrproject-rtos/zephyr
      west-commands: scripts/west-commands.yml
      import: true
      
  self:
    path: application   
