set (WAMR_BUILD_INTERP 1)
set (WAMR_BUILD_FAST_INTERP 0)
set (WAMR_BUILD_AOT 1)
set (WAMR_BUILD_JIT 0)
set (WAMR_BUILD_LIBC_BUILTIN 0)
set (WAMR_BUILD_LIBC_WASI 1)
set (WAMR_BUILD_LIB_PTHREAD 0)
set (WAMR_BUILD_LIB_WASI_THREADS 1)
set (WAMR_BUILD_REF_TYPES 1)
set (WASM_ENABLE_LOG 1)
set (WAMR_BUILD_SHARED_HEAP 1)

if (NOT DEFINED WAMR_BUILD_PLATFORM)
    set (WAMR_BUILD_PLATFORM "linux")
endif()

if (NOT DEFINED WAMR_BUILD_GLOBAL_HEAP_POOL)
    set (WAMR_BUILD_GLOBAL_HEAP_POOL 1)
endif ()
if (NOT DEFINED WAMR_BUILD_GLOBAL_HEAP_SIZE)
    set (WAMR_BUILD_GLOBAL_HEAP_SIZE 32767)
endif ()

# Set WAMR_BUILD_TARGET, currently values supported:
# "X86_64", "AMD_64", "X86_32", "AARCH64[sub]", "ARM[sub]", "THUMB[sub]",
# "MIPS", "XTENSA", "RISCV64[sub]", "RISCV32[sub]"
if (NOT DEFINED WAMR_BUILD_TARGET)
    if (CMAKE_SYSTEM_PROCESSOR MATCHES "^(arm64|aarch64)")
        set (WAMR_BUILD_TARGET "AARCH64")
        if (NOT DEFINED WAMR_BUILD_SIMD)
            set (WAMR_BUILD_SIMD 1)
        endif ()
    elseif (CMAKE_SYSTEM_PROCESSOR STREQUAL "riscv64")
        set (WAMR_BUILD_TARGET "RISCV64")
    elseif (CMAKE_SIZEOF_VOID_P EQUAL 8)
        set (WAMR_BUILD_TARGET "X86_64")
        if (NOT DEFINED WAMR_BUILD_SIMD)
            set (WAMR_BUILD_SIMD 1)
        endif ()
    elseif (CMAKE_SIZEOF_VOID_P EQUAL 4)
        set (WAMR_BUILD_TARGET "X86_32")
    else ()
        message(SEND_ERROR "Unsupported build target platform!")
    endif ()
endif ()

add_subdirectory(wasm-micro-runtime)
